# Generated by Django 5.2.6 on 2025-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userrole_role_buyerprofile_deliveryprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='nin',
            field=models.CharField(max_length=11),
        ),
    ]
